apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ms-trifork-books-mgmt-dal-native
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - image: gcr.io/trifork-api/ms-trifork-books-mgmt-dal:1.0.0-native
        env:
        - name: SYS_LOGGING_LEVEL
          value: info
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
      timeoutSeconds: 30
      serviceAccountName: ms-trifork-books-mgmt-dal-sa@trifork-api.iam.gserviceaccount.com
  traffic:
  - latestRevision: true
    percent: 100
